name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # You can specify the Node.js version you need

      - name: Cheatsheet - Install dependencies
        run: npm i
        working-directory: ./cheatsheet

      - name: Cheatsheet - Build project
        run: npm run build
        working-directory: ./cheatsheet

      - name: PONG - Install dependencies
        run: npm i
        working-directory: ./samples/pong

      - name: PONG - Build project
        run: npm run build
        working-directory: ./samples/pong

      - name: Create output directory
        run: cp -r ./public ./dist && cp ../slides/slides.pdf ./dist/slides.pdf && cp -r ../samples/pong/dist ./dist/pong
        working-directory: ./cheatsheet

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './cheatsheet/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
